package com.migu.dto;

// Generated 2015-7-27 7:48:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "area", catalog = "migu")
public class Area implements java.io.Serializable {

    private Integer areaid;
    private Area area;
    private String name;
    private Set areas = new HashSet(0);

    public Area() {
    }

    public Area(Area area, String name, Set areas) {
        this.area = area;
        this.name = name;
        this.areas = areas;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "AREAID", unique = true, nullable = false)
    public Integer getAreaid() {
        return this.areaid;
    }

    public void setAreaid(Integer areaid) {
        this.areaid = areaid;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PAREAID")
    public Area getArea() {
        return this.area;
    }

    public void setArea(Area area) {
        this.area = area;
    }

    @Column(name = "NAME")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
    public Set getAreas() {
        return this.areas;
    }

    public void setAreas(Set areas) {
        this.areas = areas;
    }

}
