package com.migu.dto;

// Generated 2015-7-27 7:48:02 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Language generated by hbm2java
 */
//@Entity
//@Table(name = "language", catalog = "migu")
public class Language implements java.io.Serializable {

    private Integer lanid;
    private Language language;
    private String name;
    private Set languages = new HashSet(0);
    private Set singers = new HashSet(0);

    public Language() {
    }

    public Language(Language language, String name, Set languages, Set singers) {
        this.language = language;
        this.name = name;
        this.languages = languages;
        this.singers = singers;
    }

//    @Id
//    @GeneratedValue(strategy = IDENTITY)
//    @Column(name = "LANID", unique = true, nullable = false)
    public Integer getLanid() {
        return this.lanid;
    }

    public void setLanid(Integer lanid) {
        this.lanid = lanid;
    }

//    @ManyToOne(fetch = FetchType.LAZY)
//    @JoinColumn(name = "PLID")
    public Language getLanguage() {
        return this.language;
    }

    public void setLanguage(Language language) {
        this.language = language;
    }

//    @Column(name = "NAME")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

//    @OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
    public Set getLanguages() {
        return this.languages;
    }

    public void setLanguages(Set languages) {
        this.languages = languages;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
    public Set getSingers() {
        return this.singers;
    }

    public void setSingers(Set singers) {
        this.singers = singers;
    }

}
